// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANcRYxMgOu1hFylCllA98YstZnwjT_yWI',
    appId: '1:312445651150:web:25c333a53d35778ee3689f',
    messagingSenderId: '312445651150',
    projectId: 'ecampus-library',
    authDomain: 'ecampus-library.firebaseapp.com',
    storageBucket: 'ecampus-library.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbB8xO1ojP08hhgPWGifiAFKluN4Hr5k',
    appId: '1:312445651150:android:aaf4f16438771e16e3689f',
    messagingSenderId: '312445651150',
    projectId: 'ecampus-library',
    storageBucket: 'ecampus-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBuZOSkfELCROg55TKZUc6XKFavocFduI',
    appId: '1:312445651150:ios:fc6d75ab45bbc5efe3689f',
    messagingSenderId: '312445651150',
    projectId: 'ecampus-library',
    storageBucket: 'ecampus-library.appspot.com',
    androidClientId: '312445651150-c9ma47vbrk7hg61aus41309v2lf8e042.apps.googleusercontent.com',
    iosClientId: '312445651150-bp3hj9et0kud9jtodg2osn3s6tcoe91r.apps.googleusercontent.com',
    iosBundleId: 'com.ecapuslibrary.ecampusLibrary',
  );
}
